### ISSUE TITLE
get method not found

### ISSUE THREAD

**Issue by ekkis** [stealify/request-cloudflare#13]
I installed the package and when I try to make the call `requestCloudflare.promises.get(...)` I get:

```
TypeError: Cannot read properties of undefined (reading 'get')
    at Object.fetch (/Users/ekkis/dev/bank-codes/index.js:18:25)
    at Object.countries (/Users/ekkis/dev/bank-codes/index.js:31:24)
    at Object.<anonymous> (/Users/ekkis/dev/bank-codes/t:4:3)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

what am I doing wrong?

**Comment by frank-dspeed** [comment]
closed as related to : https://github.com/stealify/request-cloudflare/issues/14
